name: dbt CI

on:
  push:
    branches: ["test-ci"]
  pull_request:
    branches: [ "main" ]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Create private key
        run: |
          printf "%s" "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > private_key.p8
          chmod 600 private_key.p8

      - name: dbt deps
        run: |
          cd dbt/klineforge_dbt
          dbt deps

      - name: dbt build (CI, modified only)
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          cd dbt/klineforge_dbt
          dbt build \
            --target ci 

